DROP TABLE IF EXISTS entries;
CREATE TABLE entries(
    -- ID      INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT,
    ent     varchar(50) not null
);

INSERT INTO entries(ent) VALUES("Rachel");
INSERT INTO entries(ent) VALUES("Finn");
INSERT INTO entries(ent) VALUES("Mercedes");
INSERT INTO entries(ent) VALUES("Kurt");
INSERT INTO entries(ent) VALUES("Tina");
INSERT INTO entries(ent) VALUES("Artie");
INSERT INTO entries(ent) VALUES("Puck");
INSERT INTO entries(ent) VALUES("Quinn");
INSERT INTO entries(ent) VALUES("Santana");
INSERT INTO entries(ent) VALUES("Brittany");
INSERT INTO entries(ent) VALUES("Mike");
INSERT INTO entries(ent) VALUES("Matt");
INSERT INTO entries(ent) VALUES("Will");
INSERT INTO entries(ent) VALUES("Figgins");
INSERT INTO entries(ent) VALUES("Sue");
INSERT INTO entries(ent) VALUES("Becky");
INSERT INTO entries(ent) VALUES("Rod");
INSERT INTO entries(ent) VALUES("Andrea");
INSERT INTO entries(ent) VALUES("Jesse");
INSERT INTO entries(ent) VALUES("Shelby");
INSERT INTO entries(ent) VALUES("Terri");
INSERT INTO entries(ent) VALUES("Emma");
INSERT INTO entries(ent) VALUES("Ken");
INSERT INTO entries(ent) VALUES("Sandy");
INSERT INTO entries(ent) VALUES("Sam");
INSERT INTO entries(ent) VALUES("Blaine");
INSERT INTO entries(ent) VALUES("Lauren");
INSERT INTO entries(ent) VALUES("Jacob");
INSERT INTO entries(ent) VALUES("Dave");
INSERT INTO entries(ent) VALUES("Azimio");
INSERT INTO entries(ent) VALUES("Coach Beiste");
INSERT INTO entries(ent) VALUES("Burt");
INSERT INTO entries(ent) VALUES("Carole");
INSERT INTO entries(ent) VALUES("Carl");
INSERT INTO entries(ent) VALUES("April");
INSERT INTO entries(ent) VALUES("Holly");
INSERT INTO entries(ent) VALUES("Brian");
INSERT INTO entries(ent) VALUES("Sugar");
INSERT INTO entries(ent) VALUES("Rory");
INSERT INTO entries(ent) VALUES("Joe");
INSERT INTO entries(ent) VALUES("Sebastian");
INSERT INTO entries(ent) VALUES("Shane");
INSERT INTO entries(ent) VALUES("Cooter");
INSERT INTO entries(ent) VALUES("Brody");
INSERT INTO entries(ent) VALUES("Marley");
INSERT INTO entries(ent) VALUES("Ryder");
INSERT INTO entries(ent) VALUES("Jake");
INSERT INTO entries(ent) VALUES("Kitty");
INSERT INTO entries(ent) VALUES("Unique");
INSERT INTO entries(ent) VALUES("Cassandra");
INSERT INTO entries(ent) VALUES("Betty");
INSERT INTO entries(ent) VALUES("Adam");
INSERT INTO entries(ent) VALUES("Roz");
INSERT INTO entries(ent) VALUES("Dustin");
INSERT INTO entries(ent) VALUES("Dakota");
INSERT INTO entries(ent) VALUES("Dottie");
INSERT INTO entries(ent) VALUES("Suzie");
INSERT INTO entries(ent) VALUES("Sunshine");
INSERT INTO entries(ent) VALUES("Stoner Brett");
INSERT INTO entries(ent) VALUES("Hunter");