DROP TABLE IF EXISTS entries;
CREATE TABLE entries(
    -- ID      INTEGER PRIMARY KEY NOT NULL AUTOINCREMENT,
    ent     varchar(50) not null,
    img     varchar(50)
);

INSERT INTO entries(ent, img) VALUES("Rachel", "images/rachel.jpeg");
INSERT INTO entries(ent, img) VALUES("Finn", "images/finn.jpeg");
INSERT INTO entries(ent, img) VALUES("Mercedes", "images/mercedes.jpeg");
INSERT INTO entries(ent, img) VALUES("Kurt", "images/kurt.jpeg");
INSERT INTO entries(ent, img) VALUES("Tina", "images/tina.jpeg");
INSERT INTO entries(ent, img) VALUES("Artie", "images/artie.jpeg");
INSERT INTO entries(ent, img) VALUES("Puck", "images/puck.jpeg");
INSERT INTO entries(ent, img) VALUES("Quinn", "images/quinn.jpeg");
INSERT INTO entries(ent, img) VALUES("Santana", "images/santana.jpeg");
INSERT INTO entries(ent, img) VALUES("Brittany", "images/brittany.jpeg");
INSERT INTO entries(ent, img) VALUES("Mike", "images/mike.png");
INSERT INTO entries(ent, img) VALUES("Matt", "images/matt.jpeg");
INSERT INTO entries(ent, img) VALUES("Will", "images/will.jpeg");
INSERT INTO entries(ent, img) VALUES("Figgins", "images/figgins.jpg");
INSERT INTO entries(ent, img) VALUES("Sue", "images/sue.jpeg");
INSERT INTO entries(ent, img) VALUES("Becky", "images/becky.jpeg");
INSERT INTO entries(ent, img) VALUES("Rod", "images/rod.png");
INSERT INTO entries(ent, img) VALUES("Andrea", "images/andrea.jpeg");
INSERT INTO entries(ent, img) VALUES("Jesse", "images/jesse.jpeg");
INSERT INTO entries(ent, img) VALUES("Shelby", "images/shelby.jpeg");
INSERT INTO entries(ent, img) VALUES("Terri", "images/terri.jpeg");
INSERT INTO entries(ent, img) VALUES("Emma", "images/emma.png");
INSERT INTO entries(ent, img) VALUES("Ken", "images/ken.png");
INSERT INTO entries(ent, img) VALUES("Sandy", "images/sandy.jpeg");
INSERT INTO entries(ent, img) VALUES("Sam", "images/sam.png");
INSERT INTO entries(ent, img) VALUES("Blaine", "images/blaine.jpeg");
INSERT INTO entries(ent, img) VALUES("Lauren", "images/lauren.jpeg");
INSERT INTO entries(ent, img) VALUES("Jacob", "images/jacob.jpeg");
INSERT INTO entries(ent, img) VALUES("Dave", "images/dave.jpeg");
INSERT INTO entries(ent, img) VALUES("Azimio", "images/azimio.png");
INSERT INTO entries(ent, img) VALUES("Coach Beiste", "images/coach-beiste.jpeg");
INSERT INTO entries(ent, img) VALUES("Burt", "images/burt.png");
INSERT INTO entries(ent, img) VALUES("Carole", "images/carole.png");
INSERT INTO entries(ent, img) VALUES("Carl", "images/carl.jpeg");
INSERT INTO entries(ent, img) VALUES("April", "images/april.jpeg");
INSERT INTO entries(ent, img) VALUES("Holly", "images/holly.jpeg");
INSERT INTO entries(ent, img) VALUES("Bryan", "images/bryan.jpeg");
INSERT INTO entries(ent, img) VALUES("Sugar", "images/sugar.jpeg");
INSERT INTO entries(ent, img) VALUES("Rory", "images/rory.jpeg");
INSERT INTO entries(ent, img) VALUES("Joe", "images/joe.jpeg");
INSERT INTO entries(ent, img) VALUES("Sebastian", "images/sebastian.jpeg");
INSERT INTO entries(ent, img) VALUES("Shane", "images/shane.jpeg");
INSERT INTO entries(ent, img) VALUES("Cooter", "images/cooter.png");
INSERT INTO entries(ent, img) VALUES("Brody", "images/brody.jpeg");
INSERT INTO entries(ent, img) VALUES("Marley", "images/marley.jpeg");
INSERT INTO entries(ent, img) VALUES("Ryder", "images/ryder.jpeg");
INSERT INTO entries(ent, img) VALUES("Jake", "images/jake.jpeg");
INSERT INTO entries(ent, img) VALUES("Kitty", "images/kitty.jpeg");
INSERT INTO entries(ent, img) VALUES("Unique", "images/unique.jpeg");
INSERT INTO entries(ent, img) VALUES("Cassandra", "images/cassandra.jpeg");
INSERT INTO entries(ent, img) VALUES("Betty", "images/betty.jpg");
INSERT INTO entries(ent, img) VALUES("Adam", "images/adam.jpeg");
INSERT INTO entries(ent, img) VALUES("Roz", "images/roz.jpeg");
INSERT INTO entries(ent, img) VALUES("Dustin", "images/dustin.png");
INSERT INTO entries(ent, img) VALUES("Dakota", "images/dakota.png");
INSERT INTO entries(ent, img) VALUES("Dottie", "images/dottie.png");
INSERT INTO entries(ent, img) VALUES("Suzy", "images/suzy.jpeg");
INSERT INTO entries(ent, img) VALUES("Sunshine", "images/sunshine.jpeg");
INSERT INTO entries(ent, img) VALUES("Stoner Brett", "images/stoner-brett.jpeg");
INSERT INTO entries(ent, img) VALUES("Hunter", "images/hunter.jpeg");
INSERT INTO entries(ent, img) VALUES("Grace", "images/grace.jpeg");
INSERT INTO entries(ent, img) VALUES("Dalton", "images/dalton.jpg");